### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by Blutwurst13** [ngsxfem/ngsxfem#14]
Dear developer,

I have been trying to install ngsxfem on my windows laptop, but independet of the versions of ngsolve and ngsxfem 
 I have used, I always ran into the same problem while compiling: "SpaceTimeFESpace.cpp(67,95): error C2975: 'SpaceD': invalid template argument for 'ngfem::DiffOpDtVec', expected compile-time constant expression". 
Here are some of the programs and their versions that I have used:
- CMake 3.23.2
- Microsoft Visual Studio 17 2022
- Python 3.7.9

**Comment by schruste** [comment]
Dear @Blutwurst13 ,

Thank you for your interest and your brave tries to compile ngsxfem on Windows. At the moment noone of the development team of ngsxfem is proficient with Windows and we didn't spend any effort for supporting Windows so far. This may perhaps change in the (near) future, but no promises. For now I will have to refer you to WSL(2) or a switch to unix-based systems, sorry. 

Best,
Christoph
