### ISSUE TITLE
Specify level set function as a grid function only

### ISSUE THREAD

**Issue by walkersw** [ngsxfem/ngsxfem#17]
Is it possible to have a changing level set that is only specified through a grid function?  From the examples I have seen, it seems that an analytic function must be given.  For example, the domain evolution may be unknown a priori.

In principle, this should be doable, but I don't know how the internals work.  For the sake of simplicity, suppose I only want a piecewise linear level set function.

**Comment by hvonwah** [comment]
Sure, you can in principle use any piece-wise linear GridFunction as a level set. For example, a GridFunktion that changes in time as the solution to some transport equation.

**Comment by walkersw** [comment]
Is there an example?  What I find confusing is the line:

lsetmeshadap.CalcDeformation(levelset)

It looks like it needs to compute an "exact" deformation.

**Comment by hvonwah** [comment]
That line is only necessary if you want to consider a high-order geometry approximation. Or that what you are after?

**Comment by walkersw** [comment]
Ok, so it can be ignored.  But, for the sake of argument, if I wanted to have a piecewise quadratic level set function, how would I do it?

**Comment by hvonwah** [comment]
That immediately possible here, since the integration rules on cut elements are generated with respect to straight cuts, i.e., a piece-wise linear level set.

**Comment by walkersw** [comment]
What do you mean?  If the level set function is P2, then the cuts will not be straight.

**Comment by walkersw** [comment]
Another question, if I compute a P1 level set grid function, how do I update the ngsxfem level set machinery to accept that?

**Comment by hvonwah** [comment]
ngsxfem generates quadrature rules on cut elements, by dividing the cut element into triangles and applying standard quadrature rules on each sub-triangle in the cut element, since this is robust with respect to arbitrary cut configurations.

**Comment by walkersw** [comment]
Ok, I was starting to look at that one.  Just one more comment about the P2 cut element.  It seems you would have to cut the triangle many times to get an accurate result if the boundary curve cutting through the element is curved.

**Comment by fabianheimann** [comment]
Hi Shawn! These are interesting points. From the implementation viewpoint, there are two layers of complexity in relation to geometry approximation/ numerical integration (for the sake of simplicity I assume that we consider merely spatial functions, although there is a generalisation in regards to space-time functions): 1) P1 levelset functions 2) More complex levelset functions. If you are in the setting of 1), you can decompose the integration region into simplices and that is what xfem does to generate quadrature rules. In the setting of 2), we do not aim to generate quadrature rules for the exact implicit domain. Instead, xfem will generate a deformation function (that's the "CalcDeformation" function) so that the image of the corresponding construction of 1) under this mapping is a higher order approximation of the potentially "fancy" domain.

**Comment by fabianheimann** [comment]
So, there is a significant difference between the P1 and P2 geometry setting. For P1, you can ignore all the code parts involving the deformation such as the "CalcDeformation" function. For P2, you would -- at least following our "standard approach" -- generate the deformation and by that obtain a high order approximation to the actual "P2-Lset-induced" region.

We have different code examples within and outside this repo, but I think it would be helpful to understand a bit more details of where you aim at to be able to point you in the right direction. To make it concrete: Would the algorithmic question you have be answered by a script where we start with a discretely (Gridfunction-, P1) approximated circle which grows with time by means of a shift in the function value, and with each iteration we calculate the area of the domain by numerical integration of the integrand 1?

**Comment by walkersw** [comment]
Thanks for the clarification; I suspected the deformation was doing something like from seeing various talks on this.  I think for now, I will just stick with P1.  It sounds like P2 may require more work.  If I can get P1 to work, then we can go from there.

**Comment by ngsxfem** [comment]
Hi Shawn, 

Thanks @fabianheimann and @hvonwah for your help.

To sum up: The step from P1 straight elements to higher order curved elements by mesh deformation is pretty small, so once you have the P1-geometry approximation working for you, it should be a small step to render it higher order accurate. 

There is also an older version of the quadrature rules where you can work with subdivision to obtain more accuracy without a mesh deformation, but it's not our prefered approach. In case you need that, let us know. 

I am closing this issue for the time being as I don't see an open problem or question, but feel free to re-open if there are follow-ups.

Best, Christoph
