### ISSUE TITLE
Installation issue on WSL 2

### ISSUE THREAD

**Issue by meiyue1989** [ngsxfem/ngsxfem#18]
Dear Developer,
I installed ngsxfem using "pip3 install xfem" and it installed successfully. However, when I tried to run an example, the following error occurs. It appears that there is imported issue for a DLL.  NGsolve is installed using "pip install ngsolve-avx2" , and it can work.  The verson of linux system of WSL2 is Ubuntu-22.04. I would like to know how to address this issue. 
I thank you for your kind help.
Best,
Yue

meiyue@DESKTOP-5E5BMHC:~/softwared/ngsxfem/demos$ python3 stokescutfem.py 
================================================================
WARNING: NGSolve was compiled with Netgen 
         version v6.2.2203-46-gde0d706e but
         version v6.2.2301 is loaded at run-time!!!
================================================================
importing NGSolve-6.2.2204
Traceback (most recent call last):
  File "/home/meiyue/softwared/ngsxfem/demos/stokescutfem.py", line 76, in <module>
    from xfem import *
  File "/home/meiyue/.local/lib/python3.10/site-packages/xfem/__init__.py", line 23, in <module>
    from xfem.ngsxfem_py import *
ImportError: /home/meiyue/.local/lib/python3.10/site-packages/xfem/../xfem.libs/libngcomp-6443ae02.so: undefined symbol: _ZNK6netgen8Ngx_Mesh26MultiElementTransformationILi0ELi3EN6ngcore4SIMDIdLi2EEEEEviiPKT1_mPS5_mS8_m

**Comment by schruste** [comment]
Have you tried 
pip install xfem-avx2
?

**Comment by meiyue1989** [comment]
> Have you tried pip install xfem-avx2 ?

It works. Many thanks.
