### ISSUE TITLE
Missing string cast in spacetime/python_spacetime.cpp

### ISSUE THREAD

**Issue by schwering96** [ngsxfem/ngsxfem#21]
Hello,

I believe I found an error in spacetime/python_spacetime.cpp in line 70 (if (std::regex_match (ma->GetMaterial(BND, i), pattern))). ngsxfem couldn't compile this line without explicitly casting the GetMaterial into a string (if (std::regex_match (**string**(ma->GetMaterial(BND, i)), pattern))). With this change,  the installation worked fine on my machine.

Thank you for working on ngsxfem!

Best wishes
Paul

**Comment by schruste** [comment]
Hi Paul,

This was due to a recent change in ngsolve. It should be fixed with the recent master branch.

Best,
Christoph
