### ISSUE TITLE
Installation on ARM64

### ISSUE THREAD

**Issue by gsosajones** [ngsxfem/ngsxfem#22]
Hello,

I have a working NGSolve on my Mac M1 (arm64) that I installed through pip3. I installed ngsxfem through pip3 as well, and even though I could install it, I cannot import the library because I get this error message:

/opt/homebrew/lib/python3.11/site-packages/xfem/ngsxfem_py.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')

Any idea on how I could fix this? Thank you in advance.

Best,
Giselle

**Comment by schruste** [comment]
Hi Giselle,

I am not sure if/how it is possible to build the pip-packages on arm64, although I am surprised that pip pull the x86_64 packages at all. We will have a look at this, but it's not going to be fixed soon, I guess. I recommend installing from source (both) in the meantime. Sorry. 

@hvonwah : Do you have an idea?

Best,
Christoph

**Comment by hvonwah** [comment]
Hi @gsosajones and @schruste ,

it appears that the python 3.11 package is marked/named as 'universal2', i.e., implying that it contains both the x86_64 and arm64 packages. I fix this in the github actions.

The last time I had access to an apple arm64 computer, ngsxfem did compile, but the integrity tests failed. So if you do manage to build xfem from source, make sure to install the python packages `pytest` and `psutil`, and then run `ctest` in you build folder to see if the installation works and produces the correct results.

Best,
Henry
