### ISSUE TITLE
linelasticity_puzzle

### ISSUE THREAD

**Issue by 3406212002** [ngsxfem/ngsxfem#28]
Hi,this project is really fantastic and I'm quite interested in the file called"linelasticity.py".
I plan to conduct a 3D analysis base on this file,but things  do not go smoothly.
my level sets be like :
![图片](https://github.com/user-attachments/assets/3905c217-1888-436d-ab3e-e558d8d0bc92)

When I view the  hasneg,it is strange,it should be something like the intersection of these level sets
![图片](https://github.com/user-attachments/assets/b4053734-bc67-4e5d-84fc-09e42c2ed966)

All the code is here: 

# %%
# %% ------------------------- LOAD LIBRARIES -------------------------------
from ngsolve import *
from netgen.occ import *
from netgen.csg import *
from xfem import *
from xfem.mlset import *
import pyvista

ngsglobals.msg_level = 2

# %%
# %% --------------------------- PARAMETERS ---------------------------------
# Initial mesh diameter
initial_maxh = 0.05
# Order of finite element space
k = 2
# Stabilization parameter for Nitsche
gamma_s = 0.5
gamma_n = 10

# %%
# ----------------------------------- MAIN ------------------------------------
# %% Set up the level sets, exact solution and right-hand side
def level_sets():
    return [x - 1.5, y - 0.15, -0.15 - y]
nr_ls = len(level_sets())
rhs = CF((0, 0, -10))

# %%
# %% Geometry and mesh
geo = CSGeometry()
cube = OrthoBrick( Pnt(0, -0.5,-0.5), Pnt(2, 0.5,0) )
geo.Add (cube)
ngmesh = geo.GenerateMesh(maxh=initial_maxh)
mesh = Mesh(ngmesh)

# %%
# %% Level set and cut-information
P1 = H1(mesh, order=1)
lsetsp1 = tuple(GridFunction(P1) for i in range(nr_ls))
for i, lsetp1 in enumerate(lsetsp1):
    InterpolateToP1(level_sets()[i], lsetp1)
    DrawDC(lsetp1,2,-2, mesh, "lsetp1_{}".format(i))

# %%
# %%
square = DomainTypeArray((NEG, NEG, NEG))
with TaskManager():
    square.Compress(lsetsp1)
    boundary = square.Boundary()
    boundary.Compress(lsetsp1)

mlci = MultiLevelsetCutInfo(mesh, lsetsp1)

# %%
# %%
# Element and degrees-of-freedom markers
els_if_singe = {dtt: BitArray(mesh.ne) for dtt in boundary}
facets_gp = BitArray(mesh.nedge)
hasneg = mlci.GetElementsWithContribution(square)
Draw(BitArrayCF(hasneg), mesh, "hasneg")

# %%
# %% Finite element space
Vhbase = VectorH1(mesh, order=k, dirichlet="left", dgjumps=True)
Vh = Restrict(Vhbase, hasneg)
gfu = GridFunction(Vh)

hasif = mlci.GetElementsWithContribution(boundary)
Draw(BitArrayCF(hasif), mesh, "hasif")

for i, (dtt, els_bnd) in enumerate(els_if_singe.items()):
    els_bnd[:] = mlci.GetElementsWithContribution(dtt)
    Draw(BitArrayCF(els_bnd), mesh, "els_if_singe" + str(i))

facets_gp = GetFacetsWithNeighborTypes(mesh, a=hasneg, b=hasif,
                                       use_and=True)

els_gp = GetElementsWithNeighborFacets(mesh, facets_gp)
Draw(BitArrayCF(els_gp), mesh, "gp_elements")

u, v = Vh.TnT()
h = specialcf.mesh_size
normals = square.GetOuterNormals(lsetsp1)

# Set up the integrator symbols
dx = dCut(lsetsp1, square, definedonelements=hasneg)
ds = {dtt: dCut(lsetsp1, dtt, definedonelements=els_if_singe[dtt])
      for dtt in boundary}
dw = dFacetPatch(definedonelements=facets_gp)

def eps(u):
    return Sym(Grad(u))

E, nu = 210, 0.2
mu = E / (2*(1+nu))
lam = E * nu / ((1+nu)*(1-2*nu))

# Construct integrator
a = RestrictedBilinearForm(Vh, facet_restriction=facets_gp, check_unused=False)
a += 2 * mu * InnerProduct(eps(u), eps(v)) * dx + lam * div(u) * div(v) * dx
a += mu * gamma_s / (h**2) * (u - u.Other()) * (v - v.Other()) * dw

f = LinearForm(Vh)
f += rhs * v * dx

# Assemble and solve the linear system
f.Assemble()
a.Assemble()

gfu.vec.data = a.mat.Inverse(Vh.FreeDofs()) * f.vec

# %%
# %% Draw webgui
ind = IfPos(lsetsp1[0], 1, IfPos(lsetsp1[1], 1, IfPos(lsetsp1[2], 1, -1)))
DrawDC(ind, gfu[1], 0, mesh, "u")

vtk = VTKOutput(mesh, coefs=[*lsetsp1, 33*CF((gfu[0], gfu[1], 0))],
                names=["lset1", "lset2", "lset3", "u"], filename="vtkout",
                subdivision=3, floatsize="single", legacy=False).Do()
pyvista.set_jupyter_backend('client')
visobj = pyvista.read('vtkout.vtu')
plot = pyvista.Plotter()
arrows = visobj.glyph(scale="u", orient="u", factor=0.15, tolerance=0.03)
clipped0 = visobj.clip_scalar("lset1", invert=True) \
                    .clip_scalar("lset2", invert=True) \
                    .clip_scalar("lset3", invert=True)
visobj2 = visobj.warp_by_vector(factor=0.15)
clipped = visobj2.clip_scalar("lset1", invert=True) \
                    .clip_scalar("lset2", invert=True) \
                    .clip_scalar("lset3", invert=True)
plot.add_mesh(clipped0, label='reference conf.')
plot.add_mesh(clipped, label='deformed conf.')
plot.add_mesh(arrows, label='deform. direction')
plot.add_legend()
plot.show()

**Comment by 3406212002** [comment]
Hi,I have solved this problem by adding a parameter:   VOL_or_BND = VorB.BND
![Uploading 图片.png…]()
Now it works

**Comment by hvonwah** [comment]
Hi @3406212002 

Thank you for your interest in ngsxfem! 

Please be careful when visualising 3d meshes/objects! I believe you code did what you intended. The only issue was, that the `BitArrayCF(hasneg)` only evaluates in the interior of elements, and not on the surface (element boundaries). If you enable clipping (both under Objects-> clipping plane and Clipping -> enable) in the webgui, you can see what is going on in the interior of your 3d domain.

Using `mlci.GetElementsWithContribution(square, VOL_or_BND=BND)`, you select all the surface mesh elements (triangles) with an intersection the domain `square` but none of volume elements (tetrahedra).

I hope this helps,
Henry

**Comment by hvonwah** [comment]
I will close this issue, as I think the question is resolved

**Comment by 3406212002** [comment]
> Hi @3406212002
> 
> Thank you for your interest in ngsxfem!
> 
> Please be careful when visualising 3d meshes/objects! I believe you code did what you intended. The only issue was, that the `BitArrayCF(hasneg)` only evaluates in the interior of elements, and not on the surface (element boundaries). If you enable clipping (both under Objects-> clipping plane and Clipping -> enable) in the webgui, you can see what is going on in the interior of your 3d domain.
> 
> Using `mlci.GetElementsWithContribution(square, VOL_or_BND=BND)`, you select all the surface mesh elements (triangles) with an intersection the domain `square` but none of volume elements (tetrahedra).
> 
> I hope this helps, Henry

Hi @ hvonwah ,many thanks for your help,I will try it later.

Another small thing I wanna mention is that part of  origin code in the linelasticity.py ,`def eps:  return Sym(Grad(u))` should be written as"def eps(u) :  return Sym(Grad(u))" ,then the code  can be smooth for  later comers.

**Comment by 3406212002** [comment]
I clipping `Objects-> clipping plane` and `Clipping -> enable` in the webgui, the intersection represented is  decent as I expected,but what these triangles that appear randomly on the surface means?

**Comment by hvonwah** [comment]
The black lines are just the facets of the mesh. I think that the red/blue coloring on the surface is because the object you are drawing is not defined on the surface, resulting in some junk values being visualised when the gui tries to evaluate this on the surface mesh.

**Comment by 3406212002** [comment]
> The black lines are just the facets of the mesh. I think that the red/blue coloring on the surface is because the object you are drawing is not defined on the surface, resulting in some junk values being visualised when the gui tries to evaluate this on the surface mesh.

Thank you very much for your reply.

This means  I can  directly ignore these  junk triangles?Or will they affect the subsequent calculations?

**Comment by hvonwah** [comment]
Yes, you can ignore these in this case where the domain you are interested in is 3d, i.e., the element markers you are visualising refer to the 3d elements.
