### ISSUE TITLE
analysis of complex shape object

### ISSUE THREAD

**Issue by 3406212002** [ngsxfem/ngsxfem#29]
Hi,I am going to analysis a complex object whose level sets are hard to represent by a python list
The object is like this , a .STL file actually.
![image](https://github.com/user-attachments/assets/1b0e2788-6204-4c7e-b772-1d5f489d9748)
![image](https://github.com/user-attachments/assets/49e5d89b-7560-4f7a-9aba-2f28d60338b8)
![image](https://github.com/user-attachments/assets/df612a6f-ffae-484b-b360-3e6b806f1f1e)

Is there an available API to transform  .obj or .stl  files to  level sets ,which can be used in the analysis.

and another problem is how to set boundary condition to complex object?
For example I want to set a Dirichlet boundary condition to the bottom of the object and  set an uniformed force  to the top of the object.

**Comment by hvonwah** [comment]
Hi @3406212002,

while this is conceptually possible, creating a level set from a STL file is currently not available out of the box in ngsolve/ngsxfem. This kind of thing has been done, for example on https://doi.org/10.1016/j.jcp.2024.113127. If a fitted FEM is acceptable for your purpose, then you can generate fitted meshed from STL file with NETGEN (the mesh generator usually used with NGSolve, to which ngsxfem is an add-on package).

Best,
Henry

**Comment by hvonwah** [comment]
Glad I could help!
