### ISSUE TITLE
elasticity_problem

### ISSUE THREAD

**Issue by 3406212002** [ngsxfem/ngsxfem#30]
Hello,

I’ve encountered some issues while using the unfitted method.

I attempted to create a 4×2×2 background grid and used a level set to define a 4×1×1 beam. I applied a zero displacement boundary condition on the left side and introduced a constant body force in the negative Z direction as the load.

I expected to observe the bending deformation of a cantilever beam under self-weight, but the displacement I’m seeing appears very strange, resembling shear deformation instead.
![图片](https://github.com/user-attachments/assets/cc2f4175-8dfb-42ca-9a45-060c8749d179)

Could there be something wrong with my code? I’d greatly appreciate your advice and look forward to your response!

Below is my code:
# %% ------------------------- LOAD LIBRARIES -------------------------------
from netgen.csg import *
import netgen.meshing 
from ngsolve import *
from xfem import *
from xfem.mlset import *
import pyvista
from ngsolve.webgui import Draw

ngsglobals.msg_level = 2

# %% --------------------------- PARAMETERS ---------------------------------
initial_maxh = 1
nref = 1
k = 1

gamma_s = 0.5
gamma_n = 10

# %% ----------------------------------- MAIN ------------------------------------
def level_sets():
    return [-x - 0, y - 1, z - 1]

nr_ls = len(level_sets())
rhs = CF((0, 0, -1))

# %% Geometry and mesh
left  = Plane(Pnt(0, 0, 0), Vec(-1, 0, 0)).bc("left")
right = Plane(Pnt(4, 2, 2), Vec(1, 0, 0)).bc("right")
front = Plane(Pnt(0, 0, 0), Vec(0, -1, 0)).bc("front")
back  = Plane(Pnt(4, 2, 2), Vec(0, 1, 0)).bc("back")
bot   = Plane(Pnt(0, 0, 0), Vec(0, 0, -1)).bc("bot")
top   = Plane(Pnt(4, 2, 2), Vec(0, 0, 1)).bc("top")
cube = left * right * front * back * bot * top
geo = CSGeometry()
geo.Add(cube)
netgen_mesh = geo.GenerateMesh(maxh=0.1)
netgen_mesh.GenerateVolumeMesh()

ngsolve_mesh = Mesh(netgen_mesh)
ngsolve_mesh.GetBoundaries()

# %% Level set and cut-information
P1 = H1(ngsolve_mesh, order=1)
lsetsp1 = tuple(GridFunction(P1) for i in range(nr_ls))
for i, lsetp1 in enumerate(lsetsp1):
    InterpolateToP1(level_sets()[i], lsetp1)
    DrawDC(lsetp1, 2, -2, ngsolve_mesh, "lsetp1_{}".format(i))

square = DomainTypeArray((NEG, NEG, NEG))
with TaskManager():
    square.Compress(lsetsp1)
    boundary = square.Boundary()
    boundary.Compress(lsetsp1)

mlci = MultiLevelsetCutInfo(ngsolve_mesh, lsetsp1)

els_if_singe = {dtt: BitArray(ngsolve_mesh.ne) for dtt in boundary}
facets_gp = BitArray(ngsolve_mesh.nedge)

hasneg = mlci.GetElementsWithContribution(domain_type=square)
Draw(BitArrayCF(hasneg), ngsolve_mesh, "hasneg")

# %% Finite element space
Vhbase = VectorH1(ngsolve_mesh, order=k, dirichlet="left", dgjumps=True)
Vh = Restrict(Vhbase, hasneg)
gfu = GridFunction(Vh)

hasif = mlci.GetElementsWithContribution(boundary)
Draw(BitArrayCF(hasif), ngsolve_mesh, "hasif")

for i, (dtt, els_bnd) in enumerate(els_if_singe.items()):
    els_bnd[:] = mlci.GetElementsWithContribution(dtt)
    Draw(BitArrayCF(els_bnd), ngsolve_mesh, "els_if_singe" + str(i))

facets_gp = GetFacetsWithNeighborTypes(ngsolve_mesh, a=hasneg, b=hasif, use_and=True)

els_gp = GetElementsWithNeighborFacets(ngsolve_mesh, facets_gp)
Draw(BitArrayCF(els_gp), ngsolve_mesh, "gp_elements")

# %% Bilinear and linear forms of the weak formulation
u, v = Vh.TnT()
h = specialcf.mesh_size
normals = square.GetOuterNormals(lsetsp1)

def eps(u):
    return Sym(Grad(u))

E, nu = 210, 0.2
mu = E / (2*(1+nu))
lam = E * nu / ((1+nu)*(1-2*nu))

a = RestrictedBilinearForm(Vh, facet_restriction=facets_gp, check_unused=False)
a += 2 * mu * InnerProduct(eps(u), eps(v)) * dx + lam * div(u) * div(v) * dx
a += mu * gamma_s / (h**2) * (u - u.Other()) * (v - v.Other()) * dw

f = LinearForm(Vh)
f += rhs * v * dx

f.Assemble()
a.Assemble()

gfu.vec.data = a.mat.Inverse(Vh.FreeDofs()) * f.vec

# %% Draw webgui
ind = IfPos(lsetsp1[0], 1, IfPos(lsetsp1[1], 1, IfPos(lsetsp1[2], 1, -1)))
DrawDC(ind, gfu[1], 0, ngsolve_mesh, "u")

vtk = VTKOutput(ngsolve_mesh, coefs=[*lsetsp1, 33*CF((gfu[0], gfu[1], 0))],
                names=["lset1", "lset2", "lset3", "u"], filename="vtkout",
                subdivision=3, floatsize="single", legacy=False).Do()
pyvista.set_jupyter_backend('client')
visobj = pyvista.read('vtkout.vtu')
plot = pyvista.Plotter()
arrows = visobj.glyph(scale="u", orient="u", factor=0.15, tolerance=0.03)
clipped0 = visobj.clip_scalar("lset1", invert=True) \
                    .clip_scalar("lset2", invert=True) \
                    .clip_scalar("lset3", invert=True)
visobj2 = visobj.warp_by_vector(factor=0.15)
clipped = visobj2.clip_scalar("lset1", invert=True) \
                    .clip_scalar("lset2", invert=True) \
                    .clip_scalar("lset3", invert=True)
plot.add_mesh(clipped0, label='reference conf.')
plot.add_mesh(clipped, label='deformed conf.')
plot.add_mesh(arrows, label='deform. direction')
plot.add_legend()
plot.show()

**Comment by schruste** [comment]
Hi. Are you sure that the "warp_by_vector" and "arrows" gets the right vector in? 
Anyhow: Can you post your code in raw or code format, then I will try to have a look. Best, Christoph

**Comment by 3406212002** [comment]
> Hi. Are you sure that the "warp_by_vector" and "arrows" gets the right vector in? Anyhow: Can you post your code in raw or code format, then I will try to have a look. Best, Christoph
 Hi,@schruste ,thanks for your responds.
Here is my python script: 
[test_beam.zip](https://github.com/user-attachments/files/18078198/test_beam.zip)

**Comment by schruste** [comment]
Further: Your DrawDC also works, but you should take look at gfu[2] instead of gfu[1].

**Comment by schruste** [comment]
OK, and: you put the third component to zero in your vtk-output. hence, you will not get a deformation in that direction. If you put simply "coefs = [..., gfu]" everything looks sane again.

**Comment by 3406212002** [comment]
Hi，@schruste
 Thank you so much for your quick response. It really helps me a lot. I hope you have a great day!
