### ISSUE TITLE
Binder service

### ISSUE THREAD

**Issue by LavrovaO** [ngsxfem/ngsxfem#5]
Hello, 

I have a problem to run cutfem.ipynb through the binder service. Namely, I have the error with dCut: 
NameError: name 'dCut' is not defined

Could you, please, clear the point. 

Olga

**Comment by schruste** [comment]
Dear Olga,

Thanks for you interest in the package, but I cannot reproduce the problem on binder. Neither on the v2.0-branch nor on the master branch. 
If I follow https://mybinder.org/v2/gh/ngsxfem/ngsxfem-jupyter/v2.0?filepath=cutfem.ipynb and execute "Run All" , everything goes through nicely. Can you please try again and explain in more detail what you are trying to do, if the problem persists?!

Best,
Christoph

**Comment by LavrovaO** [comment]
Thank you, Christoph, a lot! 

Your link  https://mybinder.org/v2/gh/ngsxfem/ngsxfem-jupyter/v2.0?filepath=cutfem.ipynb works well. 
I have used another one https://mybinder.org/v2/gh/ngsxfem/ngsxfem-jupyter/HEAD?filepath=tutorials.ipynb
from https://github.com/ngsxfem/ngsxfem-jupyter 

Kind regards

**Comment by schruste** [comment]
I see. There is indeed an issue with the development branches of ngsxfem and ngsxfem-jupyter and the Docker. Thanks for the hint!
