### ISSUE TITLE
bus error (core dumped)

### ISSUE THREAD

**Issue by Shaoqigit** [ngsxfem/ngsxfem#7]
Dear developer,

Thanks for this library of X-FEM,this is the one most suitable for my research.
As I reported in the ngsolve forum, when the code run until the the class **CutInfo**, the whole programme crashes with **Bus error (core dumped)**
Other functions and class works well, I can creat the level set geometry such the demo case lsetgems without any problem.
I am wondering if it is a bug in the programme or it's the problem of my computers.
OS: ubuntu 20.04
ngsolve: 6.2.2102-0 (from apt)
xfem: 2.0 (from pip3)

Thanks for your reply and again this is a very great lib for the X-FEM

Best regards
Shaoqi

**Comment by schruste** [comment]
Hi,
Does the problem occur for calls from python as well as from jupyter (as I presume that you refer to in the NGSolve forum)?
Best,
Christoph

**Comment by Shaoqigit** [comment]
Hi,

Yes it occurs for calls from python and jupyter as well as load the python script in ngsolve GUI.

> Hi,
> Does the problem occur for calls from python as well as from jupyter (as I presume that you refer to in the NGSolve forum)?
> Best,
> Christoph

**Comment by schruste** [comment]
Weird. Perhaps the ngsolve-version and ngsxfem-versions are not compatible (note that v2.0 of ngsxfem is known to be compatible with NGSolve "6.2.2101-139") . Could you please try the most recent versions, i.e. the following:
```
sudo apt-add-repository universe
sudo add-apt-repository ppa:ngsolve/nightly
sudo apt-get update

pip3 install git+https://github.com/ngsxfem/ngsxfem.git@master
```
Best,
Christoph

**Comment by Shaoqigit** [comment]
Thanks !
Rightnow there is no error, so may be this is bug of the compatibility?
The initial ngsolve I used is the 6.2.2102, should works with ngsxfem 2.0.

**Comment by schruste** [comment]
Sadly ngsolve is not always backward compatible on the C++-level. Hence, NGSolve version can also be too new for an ngsxfem release.
Best,
Christoph
